/*2. Liste os campos ID_PEDIDO, DATA_EMISSAO e VLR_TOTAL da tabela TB_PEDIDO,
seguidos de NOME do vendedor da tabela TB_EMPREGADO;*/

select  
TP.ID_PEDIDO
,TP.DATA_EMISSAO
,TP.VLR_TOTAL
,TE.NOME
from TB_PEDIDO AS TP
JOIN TB_EMPREGADO AS TE ON TP.ID_EMPREGADO = TE.ID_EMPREGADO


/*3. Liste os campos ID_PEDIDO, DATA_EMISSAO e VLR_TOTAL da tabela TB_PEDIDO,
seguidos de NOME do cliente da tabela TB_CLIENTE;*/

SELECT
TP.ID_PEDIDO
,TP.DATA_EMISSAO
,TP.VLR_TOTAL
,TC.NOME

FROM TB_PEDIDO AS TP

JOIN TB_CLIENTE AS TC ON TP.ID_PEDIDO = TP.ID_PEDIDO

/*4. Liste os pedidos com o nome do vendedor e o nome do cliente;*/
SELECT *
FROM TB_PEDIDO

select  
TP.ID_PEDIDO
,TP.DATA_EMISSAO
,TP.VLR_TOTAL
,TE.NOME NOME_VENDEDOR
,TC.NOME NOME_CLIENTE
from TB_PEDIDO AS TP
JOIN TB_EMPREGADO AS TE ON TP.ID_EMPREGADO = TE.ID_EMPREGADO
JOIN TB_CLIENTE AS TC ON TP.ID_CLIENTE = TC.ID_CLIENTE

/*5. Liste os pedidos com o nome do vendedor e o cargo do vendedor;*/
select  
TP.ID_PEDIDO
,TP.DATA_EMISSAO
,TP.VLR_TOTAL
,TE.NOME NOME_VENDEDOR
,TCAR.CARGO

from TB_PEDIDO AS TP
JOIN TB_EMPREGADO AS TE ON TP.ID_EMPREGADO = TE.ID_EMPREGADO
JOIN TB_CARGO AS TCAR ON TE.ID_CARGO = TCAR.ID_CARGO

/*6. Liste os itens de pedido (TB_ITENSPEDIDO) com o nome do produto (TB_PRODUTO.
DESCRICAO);*/

SELECT
TI.ID_PEDIDO
,TI.ITEM
,TROD.DESCRICAO

FROM TB_ITENSPEDIDO TI
JOIN TB_PRODUTO AS TROD ON TI.ID_PRODUTO = TROD.ID_PRODUTO
ORDER BY ID_PEDIDO

/*7. Liste os itens pedidos, o nome do produto e a cor (TB_COR);*/
SELECT
TI.ID_PEDIDO
,TI.ITEM
,TCOR.COR

FROM TB_ITENSPEDIDO TI
JOIN TB_COR AS TCOR ON TI.ID_COR = TCOR.ID_COR
ORDER BY ID_PEDIDO

/*8. Liste os campos ID_PRODUTO e DESCRICAO da tabela TB_PRODUTO, seguidos da
descrição do tipo de produto (TB_TIPOPRODUTO.TIPO);*/
SELECT 
TP.ID_PRODUTO
,TP.DESCRICAO
,TIP.TIPO DESCRICAO_TIPO_PRODUTO

FROM TB_PRODUTO TP
JOIN TB_TIPOPRODUTO AS TIP ON TP.ID_TIPO = TIP.ID_TIPO
ORDER BY DESCRICAO_TIPO_PRODUTO

/*9. Liste os campos ID_PRODUTO e DESCRICAO da tabela TB_PRODUTO, seguidos
da descrição do tipo de produto (TB_TIPOPRODUTO.TIPO) e do nome da unidade de
medida (TB_UNIDADE.UNIDADE)*/
SELECT 
TP.ID_PRODUTO
,TP.DESCRICAO
,TIP.TIPO DESCRICAO_TIPO_PRODUTO
,TU.UNIDADE
FROM TB_PRODUTO TP
JOIN TB_TIPOPRODUTO AS TIP ON TP.ID_TIPO = TIP.ID_TIPO
JOIN TB_UNIDADE AS TU ON TP.id_unidade = TU.ID_UNIDADE
ORDER BY DESCRICAO_TIPO_PRODUTO

/*10. Liste os campos NUM_PEDIDO, NUM_ITEM, ID_PRODUTO, QUANTIDADE e PR_
UNITARIO da tabela TB_ITENSPEDIDO, e os campos COD_PRODUTO e DESCRICAO da
tabela TB_PRODUTO, seguidos da descrição do tipo de produto (TB_TIPOPRODUTO.
TIPO) e do nome da unidade de medida (TB_UNIDADE.UNIDADE);*/
SELECT 
TI.ID_PEDIDO NUM_PEDIDO
,TI.ITEM NUM_ITEM
,TI.ID_PRODUTO
,TI.QUANTIDADE
,TI.PR_UNITARIO
,TP.ID_PRODUTO COD_PRODUTO
,TP.DESCRICAO
,TIP.TIPO DESCRICAO_TIPO_PRODUTO
,TU.UNIDADE

FROM TB_ITENSPEDIDO TI
JOIN TB_PRODUTO AS TP ON TI.ID_PRODUTO = TP.ID_PRODUTO
JOIN TB_TIPOPRODUTO AS TIP ON TP.ID_TIPO = TIP.ID_TIPO
JOIN TB_UNIDADE AS TU ON TP.id_unidade = TU.ID_UNIDADE
ORDER BY NUM_PEDIDO

/*11. Liste os campos NUM_PEDIDO, NUM_ITEM, ID_PRODUTO, QUANTIDADE e PR_
UNITARIO da tabela TB_ITENSPEDIDO, e os campos ID_PRODUTO e DESCRICAO da
tabela TB_PRODUTO, seguidos da descrição do tipo de produto (TB_TIPOPRODUTO.
TIPO), do nome da unidade de medida (TB_UNIDADE.UNIDADE) e do nome da cor
(TB_COR.COR);*/
SELECT 
TI.ID_PEDIDO NUM_PEDIDO
,TI.ITEM NUM_ITEM
,TI.ID_PRODUTO
,TI.QUANTIDADE
,TI.PR_UNITARIO
,TP.ID_PRODUTO COD_PRODUTO
,TP.DESCRICAO
,TIP.TIPO DESCRICAO_TIPO_PRODUTO
,TU.UNIDADE
,TCOR.COR

FROM TB_ITENSPEDIDO TI
JOIN TB_PRODUTO AS TP ON TI.ID_PRODUTO = TP.ID_PRODUTO
JOIN TB_TIPOPRODUTO AS TIP ON TP.ID_TIPO = TIP.ID_TIPO
JOIN TB_UNIDADE AS TU ON TP.id_unidade = TU.ID_UNIDADE
JOIN TB_COR AS TCOR ON TI.ID_COR = TCOR.ID_COR
ORDER BY NUM_PEDIDO

/*12. Liste todos os pedidos (TB_PEDIDO) do vendedor MARCELO em Jan/2017;*/
select  
TP.ID_PEDIDO
,TP.DATA_EMISSAO
,TP.VLR_TOTAL
,TE.NOME NOME_VENDEDOR


from TB_PEDIDO AS TP
JOIN TB_EMPREGADO AS TE ON TP.ID_EMPREGADO = TE.ID_EMPREGADO
WHERE 
year(TP.DATA_EMISSAO)=2017 and month(TP.DATA_EMISSAO)=1
 and TE.NOME='MARCELO'
 
/*13. Liste os nomes dos clientes (TB_CLIENTE.NOME) que efetuaram compras em
janeiro de 2018;*/
select  
TP.ID_PEDIDO
,TP.DATA_EMISSAO
,TP.VLR_TOTAL
,TC.NOME NOME_CLIENTE
from TB_PEDIDO AS TP
JOIN TB_CLIENTE AS TC ON TP.ID_CLIENTE = TC.ID_CLIENTE
WHERE 
year(TP.DATA_EMISSAO)=2018 and month(TP.DATA_EMISSAO)=1


/*14. Liste os nomes de produtos (TB_PRODUTO.DESCRICAO) que foram vendidos em
janeiro de 2019;*/
select  
TP.ID_PEDIDO
,TP.DATA_EMISSAO
,TP.VLR_TOTAL
,TPROD.DESCRICAO

from TB_PEDIDO AS TP
JOIN TB_ITENSPEDIDO AS TIP ON TP.ID_PEDIDO = TIP.ID_PEDIDO
JOIN TB_PRODUTO AS TPROD ON TIP.ID_PRODUTO = TPROD.ID_PRODUTO

WHERE 
year(TP.DATA_EMISSAO)=2019 and month(TP.DATA_EMISSAO)=1


/*15. Liste NUM_PEDIDO, VLR_TOTAL (PEDIDOS) e NOME (TB_CLIENTE). Mostre
apenas pedidos de janeiro de 2017 do estado de SP;*/
select  
TP.ID_PEDIDO
,TP.DATA_EMISSAO
,TP.VLR_TOTAL
,TC.NOME NOME_CLIENTE
,TE.ESTADO
from TB_PEDIDO AS TP
JOIN TB_CLIENTE AS TC ON TP.ID_CLIENTE = TC.ID_CLIENTE
JOIN TB_ENDERECO AS TE ON TP.ID_CLIENTE = TE.ID_CLIENTE
WHERE 
year(TP.DATA_EMISSAO)=2017 and month(TP.DATA_EMISSAO)=1
AND TE.ESTADO='SP'


/*16. Liste NUM_PEDIDO, QUANTIDADE vendida e PR_UNITARIO (TB_ITENSPEDIDO),
DESCRICAO (TB_PRODUTO), NOME do vendedor que vendeu cada item de pedido
(TB_VENDEDOR);*/
SELECT 
TI.ID_PEDIDO NUM_PEDIDO
,TI.QUANTIDADE
,TI.PR_UNITARIO
,TP.DESCRICAO

,TE.NOME NOME_VENDEDOR

FROM TB_ITENSPEDIDO TI
JOIN TB_PRODUTO AS TP ON TI.ID_PRODUTO = TP.ID_PRODUTO

JOIN TB_PEDIDO AS TPED ON TI.ID_PEDIDO = TPED.ID_PEDIDO
JOIN TB_EMPREGADO AS TE ON TPED.ID_EMPREGADO = TE.ID_EMPREGADO
ORDER BY NUM_PEDIDO



/*17. Liste o número do pedido e o valor dos pedidos de cor verde de 2018;*/
SELECT 
TI.ID_PEDIDO NUM_PEDIDO
,TI.ITEM NUM_ITEM
,TI.ID_PRODUTO
,TI.QUANTIDADE
,TI.PR_UNITARIO
,TP.ID_PRODUTO COD_PRODUTO
,TP.DESCRICAO
,TIP.TIPO DESCRICAO_TIPO_PRODUTO
,TU.UNIDADE
,TCOR.COR

FROM TB_ITENSPEDIDO TI
JOIN TB_PRODUTO AS TP ON TI.ID_PRODUTO = TP.ID_PRODUTO
JOIN TB_TIPOPRODUTO AS TIP ON TP.ID_TIPO = TIP.ID_TIPO
JOIN TB_UNIDADE AS TU ON TP.id_unidade = TU.ID_UNIDADE
JOIN TB_COR AS TCOR ON TI.ID_COR = TCOR.ID_COR
WHERE TCOR.COR='VERDE'
AND year(TI.DATA_ENTREGA)=2018

/*18. Liste os clientes de SP que realizaram compras em fevereiro de 2017;*/
select  
--TP.ID_PEDIDO
--,TP.DATA_EMISSAO
--,TP.VLR_TOTAL
TC.NOME NOME_CLIENTE
,TP.DATA_EMISSAO
--,TE.ESTADO
from TB_PEDIDO AS TP
JOIN TB_CLIENTE AS TC ON TP.ID_CLIENTE = TC.ID_CLIENTE
JOIN TB_ENDERECO AS TE ON TP.ID_CLIENTE = TE.ID_CLIENTE
WHERE 
year(TP.DATA_EMISSAO)=2017 and month(TP.DATA_EMISSAO)=2
AND TE.ESTADO='SP'



/*19. Liste os produtos fornecidos pelos fornecedores que iniciam com a letra A.*/
SELECT
TPROD.ID_PRODUTO
,TPROD.DESCRICAO
,TF.NOME NOME_FORNECEDOR

FROM TB_PRODUTO_FORNECEDOR AS TPF
JOIN TB_FORNECEDOR AS TF ON TPF.ID_FORNECEDOR = TF.ID_FORNECEDOR
JOIN TB_PRODUTO AS TPROD ON TPF.ID_PRODUTO = TPROD.ID_PRODUTO
WHERE TF.NOME LIKE 'A%'